run:
  name: onprem-middleware-avdf
  redaction: strict
  offline_only: true
  parallelism: 4

oci:
  enabled: false
  regions: []
  compartments: all
  services: all

onprem_db:
  enabled: false

onprem_middleware:
  enabled: true
  targets:
    - type: avdf
      name: replace-avdf-deployment
      config_path: /replace/with/exported-config/avdf.json
      read_config_only: true
