run:
  name: template-oci-observability-dr
  redaction: strict
  offline_only: false
  parallelism: 8

oci:
  enabled: true
  auth: instance_principal
  tenancy_ocid: "[REPLACE_TENANCY_OCID]"
  regions: [sa-santiago-1]
  compartments: all
  services: [audit, logging, logging_analytics, monitoring, events, notifications, threat_intelligence, disaster_recovery]

onprem_db:
  enabled: false

onprem_middleware:
  enabled: false
